# Generated by Django 5.0.14 on 2026-08-04 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VISTORIA', 'Vistoria Técnica'), ('INSTALACAO', 'Instalação Fotovoltaica')], max_length=12, verbose_name='Tipo de OS')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=15, verbose_name='Status')),
                ('data_agendada', models.DateField(verbose_name='Data agendada')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('status_pill_text', models.CharField(blank=True, help_text='Ex.: INSTALAÇÃO FINALIZADA, VISTORIA APROVADA, APROVADO COM RESSALVAS', max_length=60, verbose_name='Selo de status (PDF)')),
                ('cover_footnote', models.CharField(blank=True, help_text='Frase curta em itálico resumindo o resultado', max_length=200, verbose_name='Rodapé da capa (PDF)')),
                ('narrativa_paragrafos', models.TextField(blank=True, help_text='2 a 3 parágrafos, separados por linha em branco', verbose_name='Narrativa (PDF)')),
                ('resumo_tecnico_bullets', models.TextField(blank=True, help_text='Um item por linha. Se deixado em branco, é pré-preenchido com os itens do checklist marcados.', verbose_name='Resumo técnico (PDF)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='relatorios_os/', verbose_name='PDF gerado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente')),
                ('tecnico', models.ForeignKey(limit_choices_to={'role': 'tecnico'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OsFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ordens_fotos/', verbose_name='Foto')),
                ('titulo_secao', models.CharField(max_length=150, verbose_name='Título da seção')),
                ('legenda', models.TextField(blank=True, verbose_name='Legenda técnica')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Foto da OS',
                'verbose_name_plural': 'Fotos da OS',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OsChecklistResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado', models.BooleanField(default=False, verbose_name='Marcado')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='checklists.checklistitem')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_checklist', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Resposta de checklist',
                'verbose_name_plural': 'Respostas de checklist',
                'ordering': ['item__ordem'],
                'unique_together': {('os', 'item')},
            },
        ),
    ]
