# Generated by Django 6.0.7 on 2026-08-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oschecklistresposta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_fotos/', verbose_name='Foto da resposta'),
        ),
        migrations.AddField(
            model_name='oschecklistresposta',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Resposta em texto'),
        ),
    ]
