# Generated by Django 6.0.7 on 2026-08-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
        ('ordens', '0003_ordemservico_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo',
            field=models.CharField(choices=[('VISTORIA', 'Vistoria Técnica'), ('INSTALACAO', 'Instalação Fotovoltaica'), ('MATERIAL', 'Fornecimento de Material')], max_length=12, verbose_name='Tipo de OS'),
        ),
        migrations.CreateModel(
            name='OsMaterialUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='financas.materialcatalogo')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_usados', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Material usado na OS',
                'verbose_name_plural': 'Materiais usados na OS',
            },
        ),
    ]
