# Generated by Django 6.0.7 on 2026-08-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0004_alter_ordemservico_tipo_osmaterialuso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo',
            field=models.CharField(choices=[('VISTORIA', 'Vistoria Técnica'), ('INSTALACAO', 'Instalação Fotovoltaica')], max_length=12, verbose_name='Tipo de OS'),
        ),
    ]
