# Generated by Django 6.0.7 on 2026-08-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_custoextracatalogo'),
        ('ordens', '0005_alter_ordemservico_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsCustoExtraUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado', models.BooleanField(default=False, verbose_name='Marcado')),
                ('texto', models.TextField(blank=True, verbose_name='Texto')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='custos_extra_fotos/', verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='financas.custoextracatalogo')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_extras', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Custo extra usado na OS',
                'verbose_name_plural': 'Custos extras usados na OS',
                'unique_together': {('os', 'custo')},
            },
        ),
    ]
