# Generated by Django 6.0.7 on 2026-08-05 00:00

import django.db.models.deletion
from django.db import migrations, models


def copiar_fotos_existentes(apps, schema_editor):
    OsCustoExtraUso = apps.get_model('ordens', 'OsCustoExtraUso')
    OsCustoExtraFoto = apps.get_model('ordens', 'OsCustoExtraFoto')
    for uso in OsCustoExtraUso.objects.all():
        if uso.foto:
            OsCustoExtraFoto.objects.create(uso=uso, foto=uso.foto.name)


def reverter_fotos_copiadas(apps, schema_editor):
    OsCustoExtraFoto = apps.get_model('ordens', 'OsCustoExtraFoto')
    OsCustoExtraFoto.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0006_oscustoextrauso'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscustoextrauso',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.CreateModel(
            name='OsCustoExtraFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='custos_extra_fotos/', verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordens.oscustoextrauso')),
            ],
            options={
                'verbose_name': 'Foto de custo extra',
                'verbose_name_plural': 'Fotos de custo extra',
                'ordering': ['criado_em'],
            },
        ),
        migrations.RunPython(copiar_fotos_existentes, reverter_fotos_copiadas),
        migrations.RemoveField(
            model_name='oscustoextrauso',
            name='foto',
        ),
    ]
