# Generated by Django 6.0.7 on 2026-08-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0007_oscustoextrauso_quantidade_multiplas_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='descricao_recibo',
            field=models.TextField(blank=True, help_text='Usada no recibo do cliente. Ex.: Serviço de instalação de sistema fotovoltaico conectado à rede com fornecimento de material.', verbose_name='Descrição do serviço (recibo)'),
        ),
    ]
