# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations


def corrigir_quantidades(apps, schema_editor):
    OsCustoExtraUso = apps.get_model('ordens', 'OsCustoExtraUso')
    for uso in OsCustoExtraUso.objects.select_related('custo', 'os__cliente').filter(
        custo__area_por_placa__isnull=False
    ):
        quantidade_correta = uso.os.cliente.quantidade_modulos
        if uso.quantidade != quantidade_correta:
            uso.quantidade = quantidade_correta
            uso.save(update_fields=['quantidade'])


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0009_ordemservico_documento_pdf_1_and_more'),
    ]

    operations = [
        migrations.RunPython(corrigir_quantidades, migrations.RunPython.noop),
    ]
