# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0010_corrigir_quantidade_custos_extras_por_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscustoextrauso',
            name='valor_manual',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True,
                help_text='Preencha só para sobrescrever, nesta OS específica, o valor que seria '
                'calculado automaticamente. Deixe em branco para usar o cálculo normal.',
                verbose_name='Valor manual (substitui o cálculo)',
            ),
        ),
    ]
