# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0011_oscustoextrauso_valor_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_referencia_medicao',
            field=models.DateField(
                blank=True, null=True,
                help_text='Preenchido só pelo administrativo, quando essa OS específica precisa entrar '
                'em outra semana de fechamento além da semana da data agendada. Deixe em branco no uso normal.',
                verbose_name='Data de referência da medição (admin)',
            ),
        ),
    ]
