# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0012_ordemservico_data_referencia_medicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status_pill_text',
            field=models.CharField(
                blank=True,
                choices=[('FINALIZADA', 'Finalizada'), ('PENDENTE', 'Pendente'), ('CANCELADA', 'Cancelada')],
                help_text='Finalizada, pendente ou cancelada.',
                max_length=60,
                verbose_name='Selo de status (PDF)',
            ),
        ),
    ]
