# Generated by Django 6.0.7 on 2026-08-06 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0013_alter_ordemservico_status_pill_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='documento_pdf_1',
            field=models.FileField(
                blank=True, null=True, upload_to='os_documentos/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])],
                verbose_name='Projeto (PDF)',
            ),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='documento_pdf_2',
            field=models.FileField(
                blank=True, null=True, upload_to='os_documentos/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])],
                verbose_name='Vistoria (PDF)',
            ),
        ),
    ]
