# Generated by Django 6.0.8 on 2026-09-10 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0014_alter_ordemservico_documento_pdf_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscustoextrauso',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='custos_extra_arquivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Arquivo (PDF)'),
        ),
    ]
