# Generated by Django 6.0.8 on 2026-10-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0015_oscustoextrauso_arquivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo',
            field=models.CharField(choices=[('VISTORIA', 'Vistoria Técnica'), ('INSTALACAO', 'Instalação Fotovoltaica'), ('MANUTENCAO', 'Manutenção')], max_length=12, verbose_name='Tipo de OS'),
        ),
    ]
