# Generated by Django 6.0.8 on 2026-10-08 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0011_servicocatalogo'),
        ('ordens', '0016_alter_ordemservico_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='servico',
            field=models.ForeignKey(blank=True, help_text='Serviço escolhido (hoje, só manutenção) - define o valor automático cobrado ao concluir a OS. Deixe em branco se o valor vai ser lançado como custo extra na hora.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='financas.servicocatalogo', verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_servico_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preenchido só pelo administrativo, nunca pelo líder/técnico. Substitui, só nesta OS específica, o valor automático do serviço (vistoria fixa, instalação por módulo, ou serviço de manutenção escolhido). Deixe em branco no uso normal.', max_digits=10, null=True, verbose_name='Valor manual do serviço (admin)'),
        ),
    ]
