# Generated by Django 5.0.14 on 2026-08-04 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VISTORIA', 'Vistoria Técnica'), ('INSTALACAO', 'Instalação Fotovoltaica')], max_length=12, unique=True, verbose_name='Tipo de OS')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do template')),
            ],
            options={
                'verbose_name': 'Template de checklist',
                'verbose_name_plural': 'Templates de checklist',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do item')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório para dar baixa')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Item de checklist',
                'verbose_name_plural': 'Itens de checklist',
                'ordering': ['template', 'ordem'],
            },
        ),
    ]
