# Generated by Django 6.0.7 on 2026-08-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='tipo_campo',
            field=models.CharField(choices=[('CAIXA_SELECAO', 'Caixa de seleção (sim/não)'), ('TEXTO', 'Texto'), ('FOTO', 'Foto')], default='CAIXA_SELECAO', max_length=15, verbose_name='Tipo de campo'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Pergunta / descrição do item'),
        ),
    ]
