# Generated by Django 6.0.7 on 2026-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_checklistitem_tipo_campo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='tipo',
            field=models.CharField(choices=[('VISTORIA', 'Vistoria Técnica'), ('INSTALACAO', 'Instalação Fotovoltaica'), ('MATERIAL', 'Fornecimento de Material')], max_length=12, unique=True, verbose_name='Tipo de OS'),
        ),
    ]
