# Generated by Django 6.0.7 on 2026-08-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_checklisttemplate_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='tipo',
            field=models.CharField(choices=[('VISTORIA', 'Vistoria Técnica'), ('INSTALACAO', 'Instalação Fotovoltaica')], max_length=12, unique=True, verbose_name='Tipo de OS'),
        ),
    ]
