# Generated by Django 6.0.8 on 2026-09-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_alter_checklisttemplate_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='tipo_campo',
            field=models.CharField(choices=[('CAIXA_SELECAO', 'Caixa de seleção (sim/não)'), ('TEXTO', 'Texto'), ('FOTO', 'Foto'), ('ARQUIVO_PDF', 'Arquivo (PDF)')], default='CAIXA_SELECAO', max_length=15, verbose_name='Tipo de campo'),
        ),
    ]
