# Generated by Django 6.0.8 on 2026-10-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_alter_checklistitem_tipo_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='tipo_campo',
            field=models.CharField(choices=[('CAIXA_SELECAO', 'Caixa de seleção (sim/não)'), ('TEXTO', 'Texto'), ('FOTO', 'Foto'), ('ARQUIVO_PDF', 'Arquivo (PDF)'), ('FOTO_TEXTO', 'Foto + texto')], default='CAIXA_SELECAO', max_length=15, verbose_name='Tipo de campo'),
        ),
    ]
