# Generated by Django 6.0.8 on 2026-10-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_alter_checklistitem_tipo_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='tipo',
            field=models.CharField(choices=[('VISTORIA', 'Vistoria Técnica'), ('INSTALACAO', 'Instalação Fotovoltaica'), ('MANUTENCAO', 'Manutenção')], max_length=12, unique=True, verbose_name='Tipo de OS'),
        ),
    ]
