# Generated by Django 6.0.7 on 2026-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_placa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da instalação por placa')),
                ('valor_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da instalação do padrão')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de preços',
                'verbose_name_plural': 'Configuração de preços',
            },
        ),
        migrations.CreateModel(
            name='MaterialCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Produto')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor unitário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Material do catálogo',
                'verbose_name_plural': 'Catálogo de materiais',
                'ordering': ['nome'],
            },
        ),
    ]
