# Generated by Django 6.0.7 on 2026-08-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoExtraCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Serviço / custo extra')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('tipo_campo', models.CharField(choices=[('CAIXA_SELECAO', 'Caixa de seleção (sim/não)'), ('TEXTO', 'Texto'), ('FOTO', 'Foto')], default='FOTO', max_length=15, verbose_name='Como o técnico vai registrar')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Custo extra do catálogo',
                'verbose_name_plural': 'Catálogo de custos extras',
                'ordering': ['nome'],
            },
        ),
    ]
