# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_custoextracatalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaopreco',
            name='valor_vistoria',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Valor da vistoria técnica'),
        ),
    ]
