# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_configuracaopreco_valor_vistoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoextracatalogo',
            name='area_por_placa',
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True,
                help_text='Preencha só se esse custo for cobrado por metro quadrado (ex.: impermeabilização). Quando preenchido, o valor "por unidade" acima passa a ser o valor por m², e a quantidade informada na baixa/calculadora vira quantidade de placas: valor = quantidade de placas × área por placa × valor por m². Deixe em branco pra custos cobrados por unidade simples.',
                verbose_name='Área por placa (m²)',
            ),
        ),
    ]
