# Generated by Django 6.0.8 on 2026-09-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_custoextracatalogo_area_por_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoextracatalogo',
            name='aplicavel_em',
            field=models.CharField(choices=[('INSTALACAO', 'Somente instalação'), ('VISTORIA', 'Somente vistoria'), ('AMBOS', 'Instalação e vistoria')], default='INSTALACAO', help_text='Em qual tipo de OS o técnico pode lançar esse custo extra.', max_length=12, verbose_name='Aplicável em'),
        ),
        migrations.AlterField(
            model_name='custoextracatalogo',
            name='tipo_campo',
            field=models.CharField(choices=[('CAIXA_SELECAO', 'Caixa de seleção (sim/não)'), ('TEXTO', 'Texto'), ('FOTO', 'Foto'), ('ARQUIVO_PDF', 'Arquivo (PDF)')], default='FOTO', max_length=15, verbose_name='Como o técnico vai registrar'),
        ),
    ]
