# Generated by Django 6.0.8 on 2026-10-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_seed_analise_sombreamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoextracatalogo',
            name='valor_definido_pelo_tecnico',
            field=models.BooleanField(default=False, help_text='Marque quando o preço varia de serviço pra serviço (ex.: reforma de telhado) - em vez do valor fixo do catálogo, o técnico digita o valor dessa vez específica ao registrar o custo extra.', verbose_name='Técnico informa o valor na hora'),
        ),
        migrations.AlterField(
            model_name='custoextracatalogo',
            name='tipo_campo',
            field=models.CharField(choices=[('CAIXA_SELECAO', 'Caixa de seleção (sim/não)'), ('TEXTO', 'Texto'), ('FOTO', 'Foto'), ('ARQUIVO_PDF', 'Arquivo (PDF)'), ('FOTO_TEXTO', 'Foto + texto')], default='FOTO', max_length=15, verbose_name='Como o técnico vai registrar'),
        ),
    ]
