# Generated by Django 6.0.8 on 2026-10-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_seed_reforma_telhado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custoextracatalogo',
            name='aplicavel_em',
            field=models.CharField(choices=[('INSTALACAO', 'Somente instalação'), ('VISTORIA', 'Somente vistoria'), ('AMBOS', 'Instalação e vistoria'), ('MANUTENCAO', 'Somente manutenção')], default='INSTALACAO', help_text='Em qual tipo de OS o técnico pode lançar esse custo extra.', max_length=12, verbose_name='Aplicável em'),
        ),
    ]
