# Generated by Django 6.0.8 on 2026-10-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0010_seed_manutencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Serviço')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('aplicavel_em', models.CharField(choices=[('VISTORIA', 'Vistoria Técnica'), ('INSTALACAO', 'Instalação Fotovoltaica'), ('MANUTENCAO', 'Manutenção')], default='MANUTENCAO', help_text='Em qual tipo de OS esse serviço pode ser escolhido na criação.', max_length=12, verbose_name='Tipo de OS')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Serviço do catálogo',
                'verbose_name_plural': 'Catálogo de serviços',
                'ordering': ['nome'],
            },
        ),
    ]
