# Generated by Django 6.0.7 on 2026-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='instalacao_padrao',
            field=models.BooleanField(default=False, verbose_name='Terá instalação de padrão'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='quantidade_modulos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de módulos'),
        ),
    ]
