# Generated by Django 6.0.7 on 2026-08-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_instalacao_padrao_cliente_quantidade_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precisa_material_ca',
            field=models.BooleanField(default=False, verbose_name='Vai precisar de material C.A.'),
        ),
    ]
