# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_precisa_material_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pago em'),
        ),
    ]
