# Generated by Django 6.0.7 on 2026-08-06 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_pago_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='link_localizacao',
            field=models.URLField(blank=True, verbose_name='Link da localização'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento_pdf_1',
            field=models.FileField(
                blank=True, null=True, upload_to='clientes_documentos/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])],
                verbose_name='Documento anexo 1 (PDF)',
            ),
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento_pdf_2',
            field=models.FileField(
                blank=True, null=True, upload_to='clientes_documentos/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])],
                verbose_name='Documento anexo 2 (PDF)',
            ),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_referencia_medicao',
            field=models.DateField(
                blank=True, null=True,
                help_text='Usada só para decidir em qual semana de fechamento o cliente entra. Deixe em branco para usar a data de cadastro.',
                verbose_name='Data de referência da medição',
            ),
        ),
    ]
