# Generated by Django 6.0.7 on 2026-08-06 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0006_cliente_documentos_localizacao_medicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Início da semana')),
                ('fim', models.DateField(verbose_name='Fim da semana')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_medicao', to=settings.AUTH_USER_MODEL, verbose_name='Líder')),
            ],
            options={
                'verbose_name': 'Fechamento de medição',
                'verbose_name_plural': 'Fechamentos de medição',
                'ordering': ['-inicio'],
                'unique_together': {('lider', 'inicio', 'fim')},
            },
        ),
    ]
