# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_fechamentomedicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='documento_pdf_1',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='documento_pdf_2',
        ),
    ]
