# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_cliente_documento_pdf_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_referencia_medicao',
        ),
    ]
