# Generated by Django 6.0.8 on 2026-09-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_cliente_data_referencia_medicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentomedicao',
            name='observacao_divergencia',
            field=models.TextField(blank=True, help_text='Anote aqui o que foi apurado quando o valor pago não bater com o esperado (ex.: OS que entrou na semana errada, pagamento duplicado, etc.).', verbose_name='Observação sobre divergência'),
        ),
        migrations.AddField(
            model_name='fechamentomedicao',
            name='valor_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente pela tela de Medição do líder. Só é atualizado enquanto o fechamento ainda não foi marcado como pago.', max_digits=10, null=True, verbose_name='Valor esperado'),
        ),
        migrations.AddField(
            model_name='fechamentomedicao',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha com o valor que realmente foi transferido ao líder nesse fechamento.', max_digits=10, null=True, verbose_name='Valor pago'),
        ),
    ]
