# Generated by Django 6.0.8 on 2026-09-10 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_fechamentomedicao_observacao_divergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentomedicao',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'heic'])], verbose_name='Comprovante de pagamento (foto ou PDF)'),
        ),
        migrations.AlterField(
            model_name='fechamentomedicao',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha com o valor que realmente foi transferido ao líder nesse fechamento. Ao salvar, o sistema marca automaticamente como pago se o valor bater (ou passar) o esperado, e mostra o valor pendente caso contrário.', max_digits=10, null=True, verbose_name='Valor pago'),
        ),
    ]
