# Generated by Django 6.0.8 on 2026-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_fechamentomedicao_comprovante_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentomedicao',
            name='repassar_pendente',
            field=models.BooleanField(default=True, help_text='Se ficar pago parcialmente, o valor que faltar entra automaticamente no valor esperado da semana seguinte. Desligue se for resolver essa diferença de outra forma.', verbose_name='Repassar valor pendente pra próxima semana'),
        ),
        migrations.AddField(
            model_name='fechamentomedicao',
            name='valor_pendente_ajustado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha só para sobrescrever o valor pendente calculado automaticamente (esperado − pago) - por exemplo, pra perdoar parte da diferença. É esse valor (quando preenchido) que é repassado pra próxima semana.', max_digits=10, null=True, verbose_name='Valor pendente (ajuste manual)'),
        ),
        migrations.AddField(
            model_name='fechamentomedicao',
            name='valor_repasse_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Preenchido automaticamente quando a semana anterior desse líder ficou paga parcialmente e o repasse pra próxima semana está ligado. Já está somado no valor esperado.', max_digits=10, verbose_name='Valor repassado da semana anterior'),
        ),
        migrations.AlterField(
            model_name='fechamentomedicao',
            name='valor_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente pela tela de Medição do líder (já inclui o valor repassado da semana anterior, se houver). Só é atualizado enquanto o fechamento ainda não foi marcado como pago.', max_digits=10, null=True, verbose_name='Valor esperado'),
        ),
    ]
