# Generated by Django 6.0.8 on 2026-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_fechamentomedicao_repassar_pendente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentomedicao',
            name='diagnostico_diferenca',
            field=models.TextField(blank=True, default='', help_text='Preenchido automaticamente ao salvar um valor pago que não bate com o esperado - tenta apontar qual item da semana explica a diferença. Pode ser sobrescrito ou apagado manualmente.', verbose_name='Diagnóstico automático da diferença'),
        ),
    ]
