# Generated by Django 6.0.7 on 2026-08-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrativo'), ('lider', 'Líder de equipe'), ('tecnico', 'Técnico de campo')], default='tecnico', max_length=10),
        ),
    ]
