# Generated by Django 6.0.7 on 2026-08-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_empresa_recibo',
            field=models.CharField(blank=True, help_text='Nome que aparece como "Cliente" no cabeçalho dos recibos gerados para os clientes cadastrados por este líder. Ex.: RED SOLAR.', max_length=150, verbose_name='Empresa (aparece no recibo)'),
        ),
    ]
